[project]
name = "snack-stack-ai-fvela"
version = "0.0.1"
authors = [
  { name = "Flavia Vela" }
]
description = "A voice-enabled multi-agent food delivery assistant powered by LangGraph."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE*"]
dependencies = [
  "langgraph",
  "langchain",
  "langchain-anthropic",
  "langchain-chroma",
  "langchain-huggingface",
  "langchain-openai",
  "langchain_tavily",
  "multi-key-dict",
  "deepagents",
  "ipython",
  "pytest",
  "python-dotenv",
  "sentence-transformers",
  "streamlit",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
