"""Defines constants used for the streamlit app"""
MODEL_CONFIG = "model"
MODEL_PROVIDER_CONFIG = "model_provider"
MODEL_API_KEY_CONFIG = "model_api_key"
EMBEDDINGS_MODEL_PROVIDER_CONFIG = "embeddings_model_provider"
EMBEDDINGS_MODEL_API_KEY_CONFIG = "embeddings_model_api_key"
EMBEDDINGS_MODEL_CONFIG = "embeddings_model"
SNACK_STACK_ASSISTANT_CONFIG = "snack_stack_assistant"
SNACK_STACK_ASSISTANT_INTERRUPTED="snack_stack_assistant_interrupted"
